### ISSUE TITLE
Incorrect detection of Non-termination with two reads to the same location

### ISSUE THREAD

**Issue by JonasOberhauser** [MPI-SWS/genmc#29] opened 2021-11-19 15:54 UTC
Unfortunately I don't have a minimal example but the graph on which the liveness violation is detected looks something like this:

```
// do { 
R(x, 0)
R(y, ...) // some more reads actually
R_CAS(x,1) //fail, reads from mo-maximal store to x
// } while (...);
```
After the R_CAS, GenMC reports a liveness violation.
However, if the thread would continue to run, it would read (x,1) and (possibly then do CAS (x,1 --> 2)) and eventually leave the loop.

The condition of the loop does not directly depend on the result of the CAS, but reading x=1 or x=2 will eventually break out of the loop.

**Comment by michaliskok** [comment] 2021-11-22 09:06
Thanks for the report. 

The graph above seems a bit odd though. If R(x, 0) and R(x, 1) are in the same iteration, GenMC should not report a violation. If they are not (and all reads of the last iteration are reading maximally), then GenMC would report that, but I do not see why it should not.

A test case or the full graph where the violation is reported would be very helpful here.

**Comment by JonasOberhauser** [comment] 2021-11-25 09:38
> The graph above seems a bit odd though. If R(x, 0) and R(x, 1) are in the same iteration, GenMC should not report a violation. 

Exactly (and as I tried to show by adding the `// do //while` comments above, the accesses are indeed in the same iteration). Unfortunately I haven't been able to trigger this strange report in a smaller example yet :/ For my smaller examples that try to reproduce the problem, GenMC correctly doesn't report anything.

**Comment by michaliskok** [comment] 2022-02-23 09:32
I am closing this since I have no way of reproducing it. If this still manifests, please submit the corresponding test case.

**Closed by michaliskok** 2022-02-23 09:32 UTC
